name: Auto_Reset_CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Reset kudo workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow enable "kudo_mobile.yml"
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh workflow enable "kudo_web.yml"
        env:
          GH_TOKEN: ${{ github.token }}
