name: Check_Club_CI

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  mobile:
    name: Check club
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: sontrinh/strava-auto
          token: ${{ secrets.PAT }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      
      - run: npm ci

      - run: node auto-clubs.js
        env:
          USERNAME: ${{ secrets.STRAVA_USERNAME }}
          PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_PAT: ${{ secrets.PAT }}
          GIST_ID: ${{ secrets.GIST_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
